# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 23:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArtigoAvaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avalia.Artigo')),
                ('avaliador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualidade', models.IntegerField(default=0, verbose_name='qualidade')),
                ('inovacao', models.IntegerField(default=0, verbose_name='inovacao')),
                ('resultados', models.IntegerField(default=0, verbose_name='resultados')),
                ('metodologia', models.IntegerField(default=0, verbose_name='metodologia')),
                ('adequacao', models.IntegerField(default=0, verbose_name='adequacao')),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avalia.Avaliacao')),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, null=True, verbose_name='nome')),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='artigo',
            name='evento',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='avalia.Evento'),
        ),
    ]
