# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avalia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='artigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avalia.Artigo'),
        ),
    ]
