# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avalia', '0002_auto_20170612_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='adequacao',
            field=models.FloatField(default=0, verbose_name='adequacao'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='inovacao',
            field=models.FloatField(default=0, verbose_name='inovacao'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='metodologia',
            field=models.FloatField(default=0, verbose_name='metodologia'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='qualidade',
            field=models.FloatField(default=0, verbose_name='qualidade'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='resultados',
            field=models.FloatField(default=0, verbose_name='resultados'),
        ),
    ]
