# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 00:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avalia', '0003_auto_20170612_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigoavaliacao',
            name='artigo',
        ),
        migrations.RemoveField(
            model_name='artigoavaliacao',
            name='avaliador',
        ),
        migrations.DeleteModel(
            name='ArtigoAvaliacao',
        ),
    ]
