# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avalia', '0004_auto_20170612_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='nota',
            field=models.FloatField(default=0, verbose_name='nota'),
        ),
    ]
